/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Auth: typeof import('./components/Auth.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    Edit: typeof import('./components/Edit.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Register: typeof import('./components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./components/SignUp.vue')['default']
    UserForm: typeof import('./components/UserForm.vue')['default']
  }
}
